baseURL = "https://ignasius-jpeg.github.io/RadixArk-Production/"
languageCode = "en-us"
title = "RadixArk Blog"
buildFuture = true

[params]
  brand = "RadixArk"
  math = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


